import os
import sys
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def build_pdf(filename):
    doc = SimpleDocTemplate(filename, pagesize=letter,
                            rightMargin=54, leftMargin=54,
                            topMargin=54, bottomMargin=54)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#111111'),
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#555555'),
        spaceAfter=25
    )
    
    heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=colors.HexColor('#0051B3'),
        spaceBefore=12,
        spaceAfter=8
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#111111'),
        spaceAfter=6
    )
    
    code_style = ParagraphStyle(
        'CodeStyle',
        parent=styles['Code'],
        fontName='Courier',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#111111')
    )
    
    note_style = ParagraphStyle(
        'NoteStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#D92626')
    )

    # Document Header
    story.append(Paragraph("美股量化交易系统安全审计报告", title_style))
    story.append(Paragraph("US Quant Market Sentiment System Security Audit Report<br/>Generated by Antigravity | Richard Parker Coder 🐾", subtitle_style))
    story.append(Spacer(1, 10))

    # Section 1
    story.append(Paragraph("一、 密钥与虚拟环境隔离校验 (.gitignore)", heading_style))
    story.append(Paragraph("已成功对系统根目录下的 <code>.gitignore</code> 文件进行了读取与审计。确认本地敏感配置文件 <code>.env</code> 以及虚拟环境 <code>.venv</code> 均已正确列入忽略名单，防止凭证泄露至代码仓库。", body_style))
    
    # Code block for gitignore
    gitignore_content = ".env\n.venv\n.DS_Store\n__pycache__/\n*.py[cod]\n*$py.class"
    gitignore_p = Paragraph(gitignore_content.replace('\n', '<br/>'), code_style)
    
    t1 = Table([[gitignore_p]], colWidths=[504])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8F9FA')),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t1)
    story.append(Spacer(1, 12))

    # Section 2
    story.append(Paragraph("二、 零信任安全过滤机制测试 (security_patch.py)", heading_style))
    story.append(Paragraph("为验证系统防御日志泄露和明文密钥输出的能力，运行了全局安全补丁代码。补丁通过 <code>ZeroTrustMaskingFilter</code> 与 <code>MaskedStdout</code> 动态拦截控制台的 <code>sys.stdout.write</code> 行为，实现了自动脱敏。", body_style))
    
    # Code block for terminal execution output
    terminal_output = "$ python3 security_patch.py\n====== 零信任安全机制测试 ======\n正在尝试打印测试密钥: MACRO_FRED_API_KEY=***\n错误测试示例: error_log -> token=***"
    terminal_p = Paragraph(terminal_output.replace('\n', '<br/>').replace(' ', '&nbsp;'), code_style)
    
    t2 = Table([[terminal_p]], colWidths=[504])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8F9FA')),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t2)
    story.append(Spacer(1, 12))

    # Audit Verdict
    story.append(Paragraph("三、 审计结论", heading_style))
    story.append(Paragraph("<b>[PASSED]</b> 系统已具备基本的零信任过滤防护，敏感凭证在控制台或日志模块中被成功屏蔽，且环境变量本地隔离逻辑符合防泄露规范。", note_style))
    
    doc.build(story)

if __name__ == '__main__':
    desktop_path = os.path.expanduser("~/Desktop/security_audit_report.pdf")
    build_pdf(desktop_path)
    print(f"PDF successfully built at: {desktop_path}")
